### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by thulasi39** [tongueroo/aws-inventory#2]
Hi,
I really not sure, How to install this.. Could you please add few extra lines how to install this?

**Comment by thulasi39** [comment]
I moved further. But when i tried to install , I am getting this below error msg.
![capture1](https://user-images.githubusercontent.com/16955857/41775253-d9e06116-7640-11e8-9370-154a95e5bed5.PNG)

**Comment by tongueroo** [comment]
@thulasi39 The tool requires a more recent version of ruby. Recommend using https://github.com/rbenv/rbenv#installation and then you can install a more recent version of ruby. FWIW, I'm using ruby 2.5.1 nowadays.
